# Generated by Django 5.0.3 on 2024-06-16 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_rename_questions_studentquestion_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='students.studentquestion')),
            ],
            options={
                'db_table': 'QuestionAnswer',
            },
        ),
    ]
