# Generated by Django 5.0.3 on 2024-06-16 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentquestion',
            old_name='questions',
            new_name='question',
        ),
    ]
